dist: trusty
sudo: required

language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install .
  - pip install coveralls

# command to run tests
script: nosetests tests --with-coverage --cover-inclusive

after_success:
  - coveralls
